# Generated by Django 5.2.5 on 2025-08-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Read', 'Read'), ('Reading', 'Reading'), ('Want to Read', 'Want to Read')]),
        ),
    ]
